---
- name: Enable Service | haproxy
  lineinfile:
    state: present
    dest: /etc/default/haproxy
    regexp: 'ENABLED\='
    line: 'ENABLED=1'
  tags:
    - haproxy

- name: "Directory Exists | {{ haproxy_runtime_root }}"
  file:
    state: directory
    path: "{{ haproxy_runtime_root }}"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    recurse: yes
    mode: 0775

- name: "Directory Exists | /etc/haproxy/fragments.d"
  file:
    state: directory
    path: "/etc/haproxy/fragments.d"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: 0775

- command: "ls -alh /etc/haproxy/fragments.d"
  register: ls-command

- debug:
    var: ls-command

- name: Upload Config Fragments | haproxy
  template:
    src: "etc/haproxy/fragments.d/{{ item.path }}"
    dest: "/etc/haproxy/fragments.d/{{ item.path }}"
  notify: Reload Service | haproxy
  when: "{{ item.when | default (True) }}"
  with_items:
    - { path: 00-global }
    - { path: 01-defaults }
    - { path: 02-error-handling, when: haproxy_error_handling_enabled }
    - { path: 03-stats,          when: haproxy_stats_enabled }
    - { path: 80-application,    when: haproxy_standard_configuration }
    - { path: 81-deployment,     when: haproxy_autodeploy_passthrough_enabled }
    - { path: 443-https,         when: haproxy_ssl_enabled }
    - { path: 65536-backend-application }
    - { path: 65537-backend-localhost }
  tags:
    - configuration
    - fragment-configuration
    - haproxy

- name: Assemble Config Fragments | haproxy
  assemble:
    src: /etc/haproxy/fragments.d
    dest: /etc/haproxy/haproxy.cfg
    delimiter: '### START FRAGMENT ###'
  tags:
    - configuration
    - fragment-configuration
    - haproxy
